language: python
sudo: false
cache:
  directories:
    - $HOME/.theano
    - $HOME/download # Sufficient to add miniconda.sh to TRAVIS cache.
    - $HOME/miniconda2 # Add the installation to TRAVIS cache.


python:
  - "2.7"
  - "3.6"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - ./.travis/travis_before_install.sh
  - export PATH=/home/travis/miniconda2/bin:$PATH

install:
  - ./.travis/travis_install.sh
  - "source activate pyenv"
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt --no-cache-dir"
  - "pip install -r requirements-dev.txt"
  - "pip install . --no-deps"

script:
  - THEANO_FLAGS='gcc.cxxflags="-march=core2"' py.test -v --cov=gelato --cov-report term-missing

after_success:
  - coveralls